module Images (ImageType(..), imageTypes, imageFn) where
import Data.Maybe (fromJust)
data ImageType = Img100 | Img1000 | Img200 | Img400 | Img500 | ImgBlock1 | ImgBlock2 | ImgBlock3 | ImgBlock4 | ImgBlock5 | ImgBroken | ImgCloud00 | ImgCloud01 | ImgCloud02 | ImgCloud10 | ImgCloud11 | ImgCloud12 | ImgCoin0 | ImgCoin1 | ImgCoin2 | ImgCoin3 | ImgDk00 | ImgDk01 | ImgDk10 | ImgDk11 | ImgFire0 | ImgFire1 | ImgFire2 | ImgFire3 | ImgFlag | ImgFlower | ImgFMonaoLJump | ImgFMonaoLShot | ImgFMonaoLSit | ImgFMonaoLSlip | ImgFMonaoLStand | ImgFMonaoLWalk1 | ImgFMonaoLWalk2 | ImgFMonaoLWalk3 | ImgFMonaoRJump | ImgFMonaoRShot | ImgFMonaoRSit | ImgFMonaoRSlip | ImgFMonaoRStand | ImgFMonaoRWalk1 | ImgFMonaoRWalk2 | ImgFMonaoRWalk3 | ImgFont | ImgGrass0 | ImgGrass1 | ImgGrass2 | ImgKinoko | ImgKoura | ImgKoura2 | ImgKuri0 | ImgKuri1 | ImgKuriDead | ImgMonaoDead | ImgMonaoLJump | ImgMonaoLSlip | ImgMonaoLStand | ImgMonaoLWalk1 | ImgMonaoLWalk2 | ImgMonaoLWalk3 | ImgMonaoRJump | ImgMonaoRSlip | ImgMonaoRStand | ImgMonaoRWalk1 | ImgMonaoRWalk2 | ImgMonaoRWalk3 | ImgMt02 | ImgMt11 | ImgMt12 | ImgMt13 | ImgMt22 | ImgNokoL0 | ImgNokoL1 | ImgNokoR0 | ImgNokoR1 | ImgPole0 | ImgPole1 | ImgSMonaoLJump | ImgSMonaoLSit | ImgSMonaoLSlip | ImgSMonaoLStand | ImgSMonaoLWalk1 | ImgSMonaoLWalk2 | ImgSMonaoLWalk3 | ImgSMonaoRJump | ImgSMonaoRSit | ImgSMonaoRSlip | ImgSMonaoRStand | ImgSMonaoRWalk1 | ImgSMonaoRWalk2 | ImgSMonaoRWalk3 | ImgTitle  deriving (Eq)
imageTypes :: [ImageType]
imageTypes = [Img100, Img1000, Img200, Img400, Img500, ImgBlock1, ImgBlock2, ImgBlock3, ImgBlock4, ImgBlock5, ImgBroken, ImgCloud00, ImgCloud01, ImgCloud02, ImgCloud10, ImgCloud11, ImgCloud12, ImgCoin0, ImgCoin1, ImgCoin2, ImgCoin3, ImgDk00, ImgDk01, ImgDk10, ImgDk11, ImgFire0, ImgFire1, ImgFire2, ImgFire3, ImgFlag, ImgFlower, ImgFMonaoLJump, ImgFMonaoLShot, ImgFMonaoLSit, ImgFMonaoLSlip, ImgFMonaoLStand, ImgFMonaoLWalk1, ImgFMonaoLWalk2, ImgFMonaoLWalk3, ImgFMonaoRJump, ImgFMonaoRShot, ImgFMonaoRSit, ImgFMonaoRSlip, ImgFMonaoRStand, ImgFMonaoRWalk1, ImgFMonaoRWalk2, ImgFMonaoRWalk3, ImgFont, ImgGrass0, ImgGrass1, ImgGrass2, ImgKinoko, ImgKoura, ImgKoura2, ImgKuri0, ImgKuri1, ImgKuriDead, ImgMonaoDead, ImgMonaoLJump, ImgMonaoLSlip, ImgMonaoLStand, ImgMonaoLWalk1, ImgMonaoLWalk2, ImgMonaoLWalk3, ImgMonaoRJump, ImgMonaoRSlip, ImgMonaoRStand, ImgMonaoRWalk1, ImgMonaoRWalk2, ImgMonaoRWalk3, ImgMt02, ImgMt11, ImgMt12, ImgMt13, ImgMt22, ImgNokoL0, ImgNokoL1, ImgNokoR0, ImgNokoR1, ImgPole0, ImgPole1, ImgSMonaoLJump, ImgSMonaoLSit, ImgSMonaoLSlip, ImgSMonaoLStand, ImgSMonaoLWalk1, ImgSMonaoLWalk2, ImgSMonaoLWalk3, ImgSMonaoRJump, ImgSMonaoRSit, ImgSMonaoRSlip, ImgSMonaoRStand, ImgSMonaoRWalk1, ImgSMonaoRWalk2, ImgSMonaoRWalk3, ImgTitle]
imageFilenames :: [String]
imageFilenames = ["100.bmp", "1000.bmp", "200.bmp", "400.bmp", "500.bmp", "block1.bmp", "block2.bmp", "block3.bmp", "block4.bmp", "block5.bmp", "broken.bmp", "cloud00.bmp", "cloud01.bmp", "cloud02.bmp", "cloud10.bmp", "cloud11.bmp", "cloud12.bmp", "coin0.bmp", "coin1.bmp", "coin2.bmp", "coin3.bmp", "dk00.bmp", "dk01.bmp", "dk10.bmp", "dk11.bmp", "fire0.bmp", "fire1.bmp", "fire2.bmp", "fire3.bmp", "flag.bmp", "flower.bmp", "fMonaoLJump.bmp", "fMonaoLShot.bmp", "fMonaoLSit.bmp", "fMonaoLSlip.bmp", "fMonaoLStand.bmp", "fMonaoLWalk1.bmp", "fMonaoLWalk2.bmp", "fMonaoLWalk3.bmp", "fMonaoRJump.bmp", "fMonaoRShot.bmp", "fMonaoRSit.bmp", "fMonaoRSlip.bmp", "fMonaoRStand.bmp", "fMonaoRWalk1.bmp", "fMonaoRWalk2.bmp", "fMonaoRWalk3.bmp", "font.bmp", "grass0.bmp", "grass1.bmp", "grass2.bmp", "kinoko.bmp", "koura.bmp", "koura2.bmp", "kuri0.bmp", "kuri1.bmp", "kuriDead.bmp", "MonaoDead.bmp", "MonaoLJump.bmp", "MonaoLSlip.bmp", "MonaoLStand.bmp", "MonaoLWalk1.bmp", "MonaoLWalk2.bmp", "MonaoLWalk3.bmp", "MonaoRJump.bmp", "MonaoRSlip.bmp", "MonaoRStand.bmp", "MonaoRWalk1.bmp", "MonaoRWalk2.bmp", "MonaoRWalk3.bmp", "mt02.bmp", "mt11.bmp", "mt12.bmp", "mt13.bmp", "mt22.bmp", "nokoL0.bmp", "nokoL1.bmp", "nokoR0.bmp", "nokoR1.bmp", "pole0.bmp", "pole1.bmp", "sMonaoLJump.bmp", "sMonaoLSit.bmp", "sMonaoLSlip.bmp", "sMonaoLStand.bmp", "sMonaoLWalk1.bmp", "sMonaoLWalk2.bmp", "sMonaoLWalk3.bmp", "sMonaoRJump.bmp", "sMonaoRSit.bmp", "sMonaoRSlip.bmp", "sMonaoRStand.bmp", "sMonaoRWalk1.bmp", "sMonaoRWalk2.bmp", "sMonaoRWalk3.bmp", "title.bmp"]
imageFn :: ImageType -> String
imageFn = fromJust . flip lookup (zip imageTypes imageFilenames)
